# Generated by Django 5.0.6 on 2024-05-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_task_remove_tasks_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='created_at',
            new_name='date',
        ),
    ]
