# Generated by Django 5.0.6 on 2024-05-31 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tasks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='updated_at',
        ),
    ]
