# Generated by Django 5.0.6 on 2024-05-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_tasks_options_rename_created_at_tasks_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date',
        ),
    ]
